apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atlas
  namespace :  {{ .Values.namespace }}
  labels:
    app: atlas
    app.kubernetes.io/name: {{ include "atlas.name" . }}
    helm.sh/chart: {{ include "atlas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "atlas.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: atlas
        app.kubernetes.io/name: {{ include "atlas.name" . }}
        helm.sh/chart: {{ include "atlas.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
      - name: atlas
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - name: web
          containerPort: 21000