apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atlas
  namespace: atlas
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: atlas
              servicePort: 21000
